### ISSUE TITLE
If argument is string, we should use default transformation

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-imgix#3]
Currently if user does not have any transformation to apply to an image, they can pass a string as argument:
```
{{ $image := partial "imgix/GetImageSRC" "/image.jpg" }}
```
instead of a dict
```
{{ $image := partial "imgix/GetImageSRC" (dict "src" "/image.jpg" "width" 500") }}
```

<del>Question</del> Task is, when a string is passed, should we assume the user needs the "default" transformation set in the site config:

```
imgix:
  domain: tnd-backpackers.imgix.net
  defaults:
    auto: format
    ch: Width,DPR
    q: 95
```

Or should we assume they don't need any transformation at all.
