### ISSUE TITLE
Add snippets to mapping configuration

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-imgix#6]
#### We beed a decent UX before considering this
---- 

For now we can map `keywords` to certain parameter.

`width: w`.

This is cool, but some complex combination of key/value pairs are often used. For example you could often add a facedetection settings which require two params:

`fit=facearea&facepad=6`

Adding the following shortcode to the mapping config:

```yaml
imgix:
  mapping:
    width: w
    face:
      fit: facearea
      facepad: 6
```
Would allow user to call given shortcodes:

```
{{ $src := partial "tnd-imgix/GetSrc (dict "src" $src" "width" 500 "snippets" (slice "face") }}
```
